---
title: "visualize data human LN without CD patients"
author: ""
date: ""
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## Load packages

```{r load-packages, warning = FALSE}

## load packages 
suppressPackageStartupMessages({
  library(dplyr)
  library(reshape2)
  library(ggplot2)
  library(cowplot)
  library(purrr)
  library(Seurat)
  library(tidyverse)
  library(ggpubr)
  library(runSeurat3)
  library(here)
  library(ggsci)
  library(pheatmap)
  library(scater)
})
```


## load seurat object 
```{r read seurat}

basedir <- here()

## load seurat object from previous analysis
seurat <- readRDS(file=paste0(basedir, "/data/AllPatCM_LNFSCMerged_seurat.rds"))

```


## remove CD pat
```{r remove CD patients}

dim(seurat)
seurat <- subset(seurat, cond %in% c("UCD", "CDsusp"), invert=T)
seurat <- subset(seurat, patient %in% c("ucd003"), invert=T)
dim(seurat)

## reprocess
res <- c(0.8,0.6,0.4,0.25)

seurat <- NormalizeData(object = seurat)
seurat <- FindVariableFeatures(object = seurat)
seurat <- ScaleData(object = seurat, verbose = FALSE)
seurat <- RunPCA(object = seurat, npcs = 30, verbose = FALSE)
seurat <- RunTSNE(object = seurat, reduction = "pca", dims = 1:20)
seurat <- RunUMAP(object = seurat, reduction = "pca", dims = 1:20)
seurat <- FindNeighbors(object = seurat, reduction = "pca", 
                        dims = 1:20)
for (i in 1:length(res)) {
    seurat <- FindClusters(object = seurat, resolution = res[i], 
                           random.seed = 1234)
    }


## remove contaminating epithelial cells from UPENN
seurat <- subset(seurat, RNA_snn_res.0.25 %in% c("10"), invert=T)
dim(seurat)
seurat <- RunPCA(object = seurat, npcs = 30, verbose = FALSE)
seurat <- RunTSNE(object = seurat, reduction = "pca", dims = 1:20)
seurat <- RunUMAP(object = seurat, reduction = "pca", dims = 1:20)

colPal <- c(pal_nejm()(7),pal_futurama()(12))[1:length(levels(seurat))]
names(colPal) <- levels(seurat)

```


## assign groups
```{r assign group}
seurat$grp <- "FRC"
seurat$grp[which(seurat$seurat_clusters %in% c("3", "6"))] <- "BEC"
seurat$grp[which(seurat$seurat_clusters %in% c("7", "9"))] <- "LEC"
seurat$grp[which(seurat$seurat_clusters %in% c("1"))] <- "SMC"

```


## visualize data {.tabset}

### clustering 
```{r visualize clustering}

## visualize input data
DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### patient 
```{r visualize patient}
colPat <- c(pal_jco()(10),pal_futurama()(12))[1:length(unique(seurat$patient))]
names(colPat) <- unique(seurat$patient)

## visualize input data
DimPlot(seurat, reduction = "umap", cols=colPat, group.by = "patient")+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### cond
```{r visualize cond}
colTon <- pal_igv()(length(unique(seurat$cond)))
names(colTon) <- unique(seurat$cond)

## visualize input data
DimPlot(seurat, reduction = "umap", cols=colTon, group.by = "cond")+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### grp
```{r visualize grp}
colGrp <- pal_uchicago()(length(unique(seurat$grp)))
names(colGrp) <- unique(seurat$grp)

## visualize input data
DimPlot(seurat, reduction = "umap", cols=colGrp, group.by = "grp")+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### origin
```{r visualize ori}
colOri <- pal_npg()(length(unique(seurat$origin)))
names(colOri) <- unique(seurat$origin)

## visualize input data
DimPlot(seurat, reduction = "umap", cols=colOri, group.by = "origin")+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```



## cnt tables {.tabset}

### col Grp
```{r cnt tables}
grps_per_Pat <- data.frame(table(seurat$patient, seurat$grp))
colnames(grps_per_Pat) <- c("patient", "group", "cnt")

ggplot(grps_per_Pat, aes(x = patient, y = cnt)) +
  geom_bar(aes(color = group, fill = group, alpha = 0.8),
           stat = "identity") +
  scale_color_manual(values = colGrp) +
  scale_fill_manual(values = colGrp) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


### col Pat
```{r cnt tables Pat}

ggplot(grps_per_Pat, aes(x = patient, y = cnt)) +
  geom_bar(aes(color = patient, fill = patient),
           stat = "identity") +
  scale_color_manual(values = colPat) +
  scale_fill_manual(values = colPat) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

### col Cond
```{r cnt tables cond}
grps_per_Pat <- data.frame(table(seurat$patient, seurat$cond))
colnames(grps_per_Pat) <- c("patient", "cond", "cnt")

ggplot(grps_per_Pat, aes(x = patient, y = cnt)) +
  geom_bar(aes(color = cond, fill = cond),
           stat = "identity") +
  scale_color_manual(values = colTon) +
  scale_fill_manual(values = colTon) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


### col dataset
```{r cnt tables dataset, fig.height=6, fig.width=12}
grps_per_Pat <- data.frame(table(seurat$patient, seurat$dataset))
colnames(grps_per_Pat) <- c("patient", "dataset", "cnt")
colDat <- c(pal_npg()(10),pal_futurama()(12))[1:length(unique(seurat$dataset))]
names(colDat) <- unique(seurat$dataset)

ggplot(grps_per_Pat, aes(x = patient, y = cnt)) +
  geom_bar(aes(color = dataset, fill = dataset),
           stat = "identity") +
  scale_color_manual(values = colDat) +
  scale_fill_manual(values = colDat) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```




## vis cluster characterization {.tabset}

```{r avg heatmap funct}
avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  
  selGenes <- selGenes$gene
  
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
  annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                       colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
    dplyr::mutate(cond = gsub("(^[0-9]_?)","",col1)) %>%
    dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      cond = colVecCond,
      celltype=colVecIdent)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
    ordVec <- levels(seurat)
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0, cluster_rows = cr, 
         cluster_cols = cc,
         color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = annotation_col, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

```


```{r marker cluster characterization}

selMarker <- list(LEC = c("PROX1", "PECAM1"),                  
                  BEC = c("CD34", "ENG", "CDH5"),
                  SMC = c("ACTA2"),
                  FRC = c("PDPN", "CCL19", "CCL21", "CLU", "CXCL13",
                          "CD34", "PI16"))

```


### avg heatmap
```{r avg heatmap cl marker, fig.height=8, fig.width=7}

selGenes <- data.frame(gene=unlist(selMarker)) %>%
  rownames_to_column(var="grp") %>% mutate(Grp=gsub(".{1}$", "", grp))
grpCnt <- selGenes %>% group_by(Grp) %>% summarise(cnt=n())
gapR <- data.frame(Grp=unique(selGenes$Grp)) %>% 
  left_join(.,grpCnt, by="Grp") %>% mutate(cumSum=cumsum(cnt)) 
ordVec <- levels(seurat)

pOut <- avgHeatmap(seurat = seurat, selGenes = selGenes,
                  colVecIdent = colPal, 
                  ordVec=ordVec,
                  gapVecR=gapR$cumSum, gapVecC=NULL,cc=T,
                  cr=F, condCol=F)

```


## save seurat object
```{r save}

saveRDS(seurat, file=paste0(basedir,
                            "/data/AllPatWithoutCM_LNFSCMerged_seurat.rds"))

```


## session info
```{r session info}
sessionInfo()
date()
```

